/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab_final_estructuras1;

/**
 *
 * @author Paula Nuñez
 */
public class resultado extends javax.swing.JPanel {

    /**
     * Creates new form resultado
     */
  
    public resultado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnEXIT = new javax.swing.JButton();
        reaccion = new javax.swing.JLabel();
        respuesta = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        tabla = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-cerca-35.png"))); // NOI18N
        BtnEXIT.setBorder(null);
        BtnEXIT.setBorderPainted(false);
        BtnEXIT.setContentAreaFilled(false);
        BtnEXIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEXITActionPerformed(evt);
            }
        });
        add(BtnEXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, -1, -1));

        reaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/monstruo-feliz.gif"))); // NOI18N
        reaccion.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/monstruo-triste.gif"))); // NOI18N
        reaccion.setEnabled(false);
        add(reaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 200, 220));

        respuesta.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        respuesta.setForeground(new java.awt.Color(255, 255, 255));
        respuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        respuesta.setText("respuesta");
        add(respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 430, -1));

        texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ganaste.png"))); // NOI18N
        texto.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/perdiste.png"))); // NOI18N
        texto.setEnabled(false);
        add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 580, 350));

        tabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/tablerohojas.png"))); // NOI18N
        add(tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEXITActionPerformed
System.exit(0);
    }//GEN-LAST:event_BtnEXITActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEXIT;
    public javax.swing.JLabel reaccion;
    javax.swing.JLabel respuesta;
    private javax.swing.JLabel tabla;
    public javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
